apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-lb
  labels:
    app: nginx-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-lb
  template:
    metadata:
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
      labels:
        app: nginx-lb
    spec:
      containers:
        - name: nginx-lb
          image: kaparora/nginx_consul_template:latest
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          command:
            - "sh"
            - "-c"
            - | 
              cat <<EOF> /etc/nginx/consul/load-balancer.conf.ctmpl
              upstream backend {
              {{ range service "web" }}
                server {{ .Address }}:{{ .Port }};
              {{ end }}
              }

              server {
                 listen 80;

                 location / {
                    proxy_pass http://backend;
                  }
              }
              EOF
              export CONSUL_HTTP_ADDR="https://${HOST_IP}:8501"
              consul-template -template "/etc/nginx/consul/load-balancer.conf.ctmpl:/etc/nginx/consul/default.conf:service nginx reload" -log-level=debug -consul-ssl-verify=false -consul-ssl &
              nginx -g 'daemon off;'
          volumeMounts:
            - name: www
              mountPath: /etc/nginx/consul
            - name: nginx-conf
              mountPath: /etc/nginx/
              
          ports:
          - containerPort: 80
      volumes:
        - name: www
          emptyDir: {}
        - name: nginx-conf
          configMap:
            name: nginx-conf 
            items:
              - key: nginx.conf
                path: nginx.conf
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: nginx-lb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;
    events {
        worker_connections  1024;
    }

    http {
        default_type  application/octet-stream;
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
        access_log  /var/log/nginx/access.log  main;
        sendfile        on;
        #tcp_nopush     on;
        keepalive_timeout  65;
        #gzip  on;
        include /etc/nginx/consul/*.conf;
    }
---
