apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: nginxdemos/hello:latest
          ports:
          - containerPort: 80
---

